/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Database.DatabaseConnection;
import LoginScreen.LoginClass;
import static LoginScreen.LoginClass.getConn;
import java.awt.Color;
import java.util.*;
import oshi.util.FormatUtil;
import Placeholders.TextPrompt;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlo
 */
public class Telas extends javax.swing.JFrame {

    /**
     * Creates new form Init
     */
    LoginScreen.LoginClass lg  = new LoginScreen.LoginClass();
    
    String active = "lblNotificacoes";
    SpecClass specClass = new SpecClass();
    DefaultListModel listModelProcessos;
    DefaultListModel listModelBlack = new DefaultListModel();
    
    Timer timer = new Timer();
    Monitorar monitorar;
    OtimizarProcessos otimizarProcessos;
    
    public Telas() throws IOException {
        this.otimizarProcessos = new OtimizarProcessos();
        this.monitorar = new Monitorar();
        inicializacao();
        initComponents();
        esconderBotoes();
        lbNomeStreamer.setText(lg.getNomeStreamer());
        
    }
    public void esconderBotoes(){
        btIn.setVisible(false);
        btOut.setVisible(false);
        btSalvarProcessos.setVisible(false);
        btSalvarSpecs.setVisible(false);
        btAtualizarSpecs.setVisible(false);
    }
    public void inicializacao() throws IOException {
        otimizarProcessos.deletarProcessos();
        monitorar.monitoramento();
        monitorar.alerta();
        timer.schedule(new RemindTask(), 10*1000);
    }

    class RemindTask extends TimerTask {
        public void run() {
            try {
                inicializacao();
            } catch (IOException ex) {
                Logger.getLogger(Telas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CorpoTela = new javax.swing.JPanel();
        btFechar = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        import_inicio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbNomeStreamer = new javax.swing.JLabel();
        import_otimizar = new javax.swing.JPanel();
        scrollProcessos = new javax.swing.JScrollPane();
        listProcessos = new javax.swing.JList<>();
        scrollBlack = new javax.swing.JScrollPane();
        listBlack = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btIn = new javax.swing.JButton();
        btOut = new javax.swing.JButton();
        btSalvarProcessos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        import_specs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        linux = new javax.swing.JLabel();
        windows = new javax.swing.JLabel();
        lbAtualizarSpecs = new javax.swing.JLabel();
        lbSalvarSpecs = new javax.swing.JLabel();
        labelsPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbSistemaOperacional = new javax.swing.JLabel();
        lbVersaoSistemaOperacional = new javax.swing.JLabel();
        lbMarcaComputador = new javax.swing.JLabel();
        lbTotalDisco = new javax.swing.JLabel();
        lbGhzProcessador = new javax.swing.JLabel();
        lbTotalMemoria = new javax.swing.JLabel();
        lbQtdMonitores = new javax.swing.JLabel();
        btAtualizarSpecs = new javax.swing.JButton();
        btSalvarSpecs = new javax.swing.JButton();
        BarraLateral = new javax.swing.JPanel();
        lblOtimizar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblSpecs = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        logoBest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CorpoTela.setBackground(new java.awt.Color(255, 255, 255));
        CorpoTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CorpoTela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close.png"))); // NOI18N
        btFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFecharMouseClicked(evt);
            }
        });
        CorpoTela.add(btFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        import_inicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(50, 0, 114));
        jLabel18.setText("Olá,");

        lbNomeStreamer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNomeStreamer.setForeground(new java.awt.Color(50, 0, 114));
        lbNomeStreamer.setText("nome do usuario");

        javax.swing.GroupLayout import_inicioLayout = new javax.swing.GroupLayout(import_inicio);
        import_inicio.setLayout(import_inicioLayout);
        import_inicioLayout.setHorizontalGroup(
            import_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_inicioLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNomeStreamer)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        import_inicioLayout.setVerticalGroup(
            import_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_inicioLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(import_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbNomeStreamer))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        main.add(import_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 580));

        import_otimizar.setBackground(new java.awt.Color(255, 255, 255));

        listProcessos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollProcessos.setViewportView(listProcessos);

        listBlack.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollBlack.setViewportView(listBlack);

        jLabel1.setText("Processos Ativos");

        btIn.setText("-->");
        btIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInActionPerformed(evt);
            }
        });

        btOut.setText("<--");
        btOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutActionPerformed(evt);
            }
        });

        btSalvarProcessos.setText("Salvar");
        btSalvarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarProcessosActionPerformed(evt);
            }
        });

        jLabel2.setText("BlackList");

        javax.swing.GroupLayout import_otimizarLayout = new javax.swing.GroupLayout(import_otimizar);
        import_otimizar.setLayout(import_otimizarLayout);
        import_otimizarLayout.setHorizontalGroup(
            import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_otimizarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSalvarProcessos)
                    .addGroup(import_otimizarLayout.createSequentialGroup()
                        .addComponent(scrollProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btOut, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(btIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(scrollBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(import_otimizarLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(155, 155, 155))
        );
        import_otimizarLayout.setVerticalGroup(
            import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_otimizarLayout.createSequentialGroup()
                .addGroup(import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(import_otimizarLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(import_otimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(import_otimizarLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btIn)
                        .addGap(39, 39, 39)
                        .addComponent(btOut)))
                .addGap(42, 42, 42)
                .addComponent(btSalvarProcessos)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        main.add(import_otimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 580));

        import_specs.setBackground(new java.awt.Color(255, 255, 255));
        import_specs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        import_specs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 0, -1, -1));

        linux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LinuxLogo.png"))); // NOI18N
        import_specs.add(linux, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 290, 390));

        windows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/winLogo.png"))); // NOI18N
        import_specs.add(windows, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 280, 410));

        lbAtualizarSpecs.setText("Deseja atualizar os dados da sua maquina?");
        import_specs.add(lbAtualizarSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 300, 20));

        lbSalvarSpecs.setText("Deseja salvar as configurações atuais?");
        import_specs.add(lbSalvarSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 290, 40));

        labelsPanel.setBackground(new java.awt.Color(254, 254, 254));
        labelsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel19.setText("Sistema Operacional:");

        jLabel20.setText("Versão do Sistema Operacional:");

        jLabel21.setText("Memória (RAM):");

        jLabel24.setText("Fabricante:");

        jLabel25.setText("Disco total:");

        jLabel26.setText("Processador:");

        jLabel27.setText("Numero de Monitores:");

        lbSistemaOperacional.setText("Sistema Operacional");

        lbVersaoSistemaOperacional.setText("Versão do Sistema Operacional");

        lbMarcaComputador.setText("Marca Computador");

        lbTotalDisco.setText("Disco Total");

        lbGhzProcessador.setText("GHz");

        lbTotalMemoria.setText("Total de Memória RAM");

        lbQtdMonitores.setText("Quantidade de Monitores");

        javax.swing.GroupLayout labelsPanelLayout = new javax.swing.GroupLayout(labelsPanel);
        labelsPanel.setLayout(labelsPanelLayout);
        labelsPanelLayout.setHorizontalGroup(
            labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(labelsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(4, 4, 4)
                            .addComponent(lbSistemaOperacional))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(2, 2, 2)
                            .addComponent(lbVersaoSistemaOperacional))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addGap(4, 4, 4)
                            .addComponent(lbQtdMonitores))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(3, 3, 3)
                            .addComponent(lbGhzProcessador))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(16, 16, 16)
                            .addComponent(lbMarcaComputador))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(11, 11, 11)
                            .addComponent(lbTotalDisco))
                        .addGroup(labelsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(6, 6, 6)
                            .addComponent(lbTotalMemoria)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        labelsPanelLayout.setVerticalGroup(
            labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(labelsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addComponent(lbSistemaOperacional))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20)
                        .addComponent(lbVersaoSistemaOperacional))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27)
                        .addComponent(lbQtdMonitores))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(lbGhzProcessador))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(lbMarcaComputador))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addComponent(lbTotalDisco))
                    .addGap(22, 22, 22)
                    .addGroup(labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(lbTotalMemoria))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        import_specs.add(labelsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 460, 290));

        btAtualizarSpecs.setBackground(new java.awt.Color(50, 0, 114));
        btAtualizarSpecs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btAtualizarSpecs.setForeground(new java.awt.Color(255, 255, 255));
        btAtualizarSpecs.setText("Atualizar Maquina");
        btAtualizarSpecs.setBorder(null);
        btAtualizarSpecs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAtualizarSpecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarSpecsActionPerformed(evt);
            }
        });
        import_specs.add(btAtualizarSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 470, 190, 50));

        btSalvarSpecs.setBackground(new java.awt.Color(50, 0, 114));
        btSalvarSpecs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btSalvarSpecs.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarSpecs.setText("Salvar Maquina");
        btSalvarSpecs.setBorder(null);
        btSalvarSpecs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvarSpecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarSpecsActionPerformed(evt);
            }
        });
        import_specs.add(btSalvarSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 146, 50));

        main.add(import_specs, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 580));

        CorpoTela.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 560));

        getContentPane().add(CorpoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 800, 620));

        BarraLateral.setBackground(new java.awt.Color(50, 0, 114));
        BarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOtimizar.setBackground(new java.awt.Color(66, 3, 155));
        lblOtimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblOtimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOtimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOtimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOtimizarMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(253, 204, 52));
        jLabel7.setText("Otimizar");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N

        javax.swing.GroupLayout lblOtimizarLayout = new javax.swing.GroupLayout(lblOtimizar);
        lblOtimizar.setLayout(lblOtimizarLayout);
        lblOtimizarLayout.setHorizontalGroup(
            lblOtimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblOtimizarLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        lblOtimizarLayout.setVerticalGroup(
            lblOtimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblOtimizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BarraLateral.add(lblOtimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 248, 50));

        lblSpecs.setBackground(new java.awt.Color(66, 3, 155));
        lblSpecs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSpecs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSpecsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSpecsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSpecsMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 204, 52));
        jLabel9.setText("Minhas Specs");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png"))); // NOI18N

        javax.swing.GroupLayout lblSpecsLayout = new javax.swing.GroupLayout(lblSpecs);
        lblSpecs.setLayout(lblSpecsLayout);
        lblSpecsLayout.setHorizontalGroup(
            lblSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblSpecsLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        lblSpecsLayout.setVerticalGroup(
            lblSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblSpecsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BarraLateral.add(lblSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 248, 50));

        logoBest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoBest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BSp.png"))); // NOI18N
        logoBest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoBestMousePressed(evt);
            }
        });
        BarraLateral.add(logoBest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 162, 82));

        getContentPane().add(BarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        setSize(new java.awt.Dimension(1048, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_btFecharMouseClicked

    private void lblOtimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtimizarMouseEntered
        lblOtimizar.setBackground(new Color(37, 13, 65));
    }//GEN-LAST:event_lblOtimizarMouseEntered

    private void lblOtimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtimizarMouseExited
        if (!(active.equalsIgnoreCase("lblOtimizar"))) {
            lblOtimizar.setBackground(new Color(66, 3, 155));
        }
    }//GEN-LAST:event_lblOtimizarMouseExited

    private void lblSpecsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpecsMouseEntered
        lblSpecs.setBackground(new Color(37, 13, 65));
    }//GEN-LAST:event_lblSpecsMouseEntered

    private void lblSpecsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpecsMouseExited
        if (!(active.equalsIgnoreCase("lblSpecs"))) {
            lblSpecs.setBackground(new Color(66, 3, 155));
        }
    }//GEN-LAST:event_lblSpecsMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void lblOtimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtimizarMousePressed
        active = "lblOtimizar";

       
        lblOtimizar.setBackground(new Color(37, 13, 65));
        lblSpecs.setBackground(new Color(66, 3, 155));
        try {
            main.removeAll();
            main.repaint();
            main.revalidate();
            main.add(import_otimizar);
            main.repaint();
            main.revalidate();
        } catch (Exception e) {
            
        }
        btIn.setVisible(true);
        btOut.setVisible(true);
        btSalvarProcessos.setVisible(true);
        try{
            monitorar.processosAtivos();
            listModelProcessos  = new DefaultListModel();
            OtimizarProcessos otm = new OtimizarProcessos();
            listModelBlack = otm.blackListBanco();
            for(int i = 0; i < monitorar.procsTotal.size(); i++){
                oshi.software.os.OSProcess p = monitorar.procsTotal.get(i);
                listModelProcessos.addElement(p.getProcessID()+" - "+p.getName()); 
            }
            listProcessos.setModel(listModelProcessos);
            listBlack.setModel(listModelBlack);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro, verifique os logs"+e);
        }
    }//GEN-LAST:event_lblOtimizarMousePressed

    private void lblSpecsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpecsMousePressed
        active = "lblSpecs";
        
        lblOtimizar.setBackground(new Color(66, 3, 155));
        lblSpecs.setBackground(new Color(37, 13, 65));
        try {
            main.removeAll();
            main.repaint();
            main.revalidate();
            main.add(import_specs);
            main.repaint();
            main.revalidate();
            
            
            
        } catch (Exception e) {
            
        }
        labelsPanel.setVisible(false);
        windows.setVisible(false);
        linux.setVisible(false);
        btSalvarSpecs.setVisible(false);
        lbSalvarSpecs.setVisible(false);
        btAtualizarSpecs.setVisible(false);
        lbAtualizarSpecs.setVisible(false);
        try{
            Boolean isTrue = specClass.verificarMaquina();
            if(isTrue){
                //SISTEMA OP
                lbSistemaOperacional.setText(specClass.getSistemaOperacional());
                lbVersaoSistemaOperacional.setText(specClass.getVersaoSistemaOperacional().toString());
                lbMarcaComputador.setText(specClass.getMarcaComputador());
                //MONITORES
                lbQtdMonitores.setText(specClass.getQtdMonitores().toString());
                //CPU
                lbGhzProcessador.setText(specClass.getGhzProcessador());
                //RAM
                lbTotalDisco.setText(String.format("%d GB",Math.round(specClass.getDiscoTotal())));
                lbTotalMemoria.setText(FormatUtil.formatBytes(specClass.getTotalMemoria()));
                
                

                if(specClass.getSistemaOperacional().equals("Ubuntu")){
                    linux.setVisible(true);
                    windows.setVisible(false);
                }else{
                    linux.setVisible(false);
                    windows.setVisible(true);
                }
                //exibir specs
                labelsPanel.setVisible(true);
                lbAtualizarSpecs.setVisible(true);
                btAtualizarSpecs.setVisible(true);
            }else{
                btSalvarSpecs.setVisible(true);
                lbSalvarSpecs.setVisible(true);
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_lblSpecsMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void btInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInActionPerformed
        listModelBlack.addElement(listProcessos.getSelectedValue());
        listBlack.setModel(listModelBlack);
    }//GEN-LAST:event_btInActionPerformed

    private void btOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutActionPerformed
        listModelBlack.removeElement(listBlack.getSelectedValue());
        listBlack.setModel(listModelBlack);
    }//GEN-LAST:event_btOutActionPerformed

    private void btSalvarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarProcessosActionPerformed
        try{
            OtimizarProcessos otimizarPro = new OtimizarProcessos();
            
            Database.DatabaseConnection conn = getConn();
            Connection connection = conn.getConnection();
            
            String deleteBlackList= "DELETE FROM processos "
            + "WHERE idMaquina = ? AND blackList = 1";
            PreparedStatement psDel = connection.prepareStatement(deleteBlackList);
            
            psDel.setInt(1, lg.getIdMaquina());
            psDel.execute();
            
            for (int i = 0; i < listModelBlack.getSize(); i++) {
                String array[] = listModelBlack.getElementAt(i).toString().split(" - ");
                otimizarPro.salvarBlackList(Integer.parseInt(array[0]),array[1]);
            }
            otimizarPro.deletarProcessos();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }      
    }//GEN-LAST:event_btSalvarProcessosActionPerformed

    private void btSalvarSpecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarSpecsActionPerformed
        try{
            specClass.criarSpecs();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarSpecsActionPerformed

    private void btAtualizarSpecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarSpecsActionPerformed
        try{
            specClass.atualizarSpecs();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btAtualizarSpecsActionPerformed

    private void logoBestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBestMousePressed
        active = "logoBest";
        
        lblOtimizar.setBackground(new Color(66, 3, 155));
        lblSpecs.setBackground(new Color(66, 3, 155));
        try {
            main.removeAll();
            main.repaint();
            main.revalidate();
            main.add(import_inicio);
            main.repaint();
            main.revalidate();
            
            
            
        } catch (Exception e) {
            
        }
        esconderBotoes();
    }//GEN-LAST:event_logoBestMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Telas().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Telas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLateral;
    private javax.swing.JPanel CorpoTela;
    private javax.swing.JButton btAtualizarSpecs;
    private javax.swing.JLabel btFechar;
    private javax.swing.JButton btIn;
    private javax.swing.JButton btOut;
    private javax.swing.JButton btSalvarProcessos;
    private javax.swing.JButton btSalvarSpecs;
    private javax.swing.JPanel import_inicio;
    private javax.swing.JPanel import_otimizar;
    private javax.swing.JPanel import_specs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel labelsPanel;
    private javax.swing.JLabel lbAtualizarSpecs;
    private javax.swing.JLabel lbGhzProcessador;
    private javax.swing.JLabel lbMarcaComputador;
    private javax.swing.JLabel lbNomeStreamer;
    private javax.swing.JLabel lbQtdMonitores;
    private javax.swing.JLabel lbSalvarSpecs;
    private javax.swing.JLabel lbSistemaOperacional;
    private javax.swing.JLabel lbTotalDisco;
    private javax.swing.JLabel lbTotalMemoria;
    private javax.swing.JLabel lbVersaoSistemaOperacional;
    private javax.swing.JPanel lblOtimizar;
    private javax.swing.JPanel lblSpecs;
    private javax.swing.JLabel linux;
    private javax.swing.JList<String> listBlack;
    private javax.swing.JList<String> listProcessos;
    private javax.swing.JLabel logoBest;
    private javax.swing.JPanel main;
    private javax.swing.JScrollPane scrollBlack;
    private javax.swing.JScrollPane scrollProcessos;
    private javax.swing.JLabel windows;
    // End of variables declaration//GEN-END:variables

}
